interga_dev/__init__.py
from flask import Flask
from flask import redirect, url_for, session, render_template
from authlib.integrations.flask_client import OAuth
from interga_dev.routes.usuarios import usuarios
from interga_dev.routes.visitantes import visitantes

oauth = OAuth()

def create_app():
  app = Flask(__name__)
  app.config['SECRET_KEY'] = "VB4028U32683476528594944"
  
  # Configuração do OAuth
  oauth.init_app(app)
  # Configuração do OAuth para o Google
  google = oauth.register(
    name='google',
    client_id="434532814222-4rae9gtph81n2tduflajo2l3cun7bo4s.apps.googleusercontent.com",  # Substitua pelo seu Client ID
    client_secret="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",  # Substitua pelo seu Client Secret  
    access_token_url='https://accounts.google.com/o/oauth2/token',
    access_token_params=None,
    authorize_url='https://accounts.google.com/o/oauth2/auth',
    authorize_params=None,
    api_base_url='https://www.googleapis.com/oauth2/v1/',
    jwks_uri='https://www.googleapis.com/oauth2/v3/certs',
    client_kwargs={'scope': 'openid email profile'}
  )
  
  @app.route('/login')
  def login():
    return render_template('login.html')
  
  @app.route('/login-google')
  def login_google():
    redirect_uri = url_for('authorize', _external=True)
    return google.authorize_redirect(redirect_uri)

  @app.route('/authorize')
  def authorize():
    token = google.authorize_access_token()
    resp = google.get('userinfo', token=token)
    user_info = resp.json()
    print(user_info)
    
    for key, value in user_info.items():
      session[key] = value
    
    if user_info['name']:
      return redirect(url_for('usuarios.perfil'))
    else:
      session['name'] = 'Usuário não identificado'
      return redirect(url_for('usuarios.perfil'))
  
  # Registrando os blueprints depois de instanciar o objeto OAuth
  app.register_blueprint(usuarios)
  app.register_blueprint(visitantes)
    
  return app

interga_dev/routes/usuario.py
from flask import redirect, url_for, session
from authlib.integrations.flask_client import OAuth
from flask import Blueprint

user = Blueprint('user', __name__, url_prefix='/usuario')

# Importe o objeto app aqui, para evitar o ciclo de importação circular
from interga_dev import create_app

# Configuração do OAuth
oauth = OAuth(create_app())
google = oauth.register(
  name='google',
  client_id="434532814222-4rae9gtph81n2tduflajo2l3cun7bo4s.apps.googleusercontent.com",  # Substitua pelo seu Client ID
  client_secret="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",  # Substitua pelo seu Client Secret  
  access_token_url='https://accounts.google.com/o/oauth2/token',
  access_token_params=None,
  authorize_url='https://accounts.google.com/o/oauth2/auth',
  authorize_params=None,
  api_base_url='https://www.googleapis.com/oauth2/v1/',
  client_kwargs={'scope': 'openid email profile'}
)

@user.route('/login')
def login():
  redirect_uri = url_for('authorize', _external=True)
  return google.authorize_redirect(redirect_uri)

@user.route('/authorize')
def authorize():
  token = google.authorize_access_token()
  resp = google.get('userinfo', token=token)
  user_info = resp.json()
  session['email'] = user_info['email']
  return redirect('/')

@user.route('/logout')
def logout():
  # handle logout request
  pass

interga_dev/routes/usuarios.py
from flask import Blueprint, redirect, url_for, session, render_template

usuarios = Blueprint('usuarios', __name__, url_prefix='/usuario')

@usuarios.route('/perfil')
def perfil():
  return render_template('usuarios/home.html')

interga_dev/routes/visitante.py
from flask import redirect, url_for, render_template, session
from flask import Blueprint

guest = Blueprint('guest', __name__, url_prefix='/')

@guest.route('')
@guest.route('/login')
def login():
  return render_template('login.html')

interga_dev/routes/visitantes.py
from flask import redirect, url_for, render_template, session
from flask import Blueprint

visitantes = Blueprint('visitantes', __name__, url_prefix='/')

@visitantes.route('')
@visitantes.route('/home')
def home():
  return render_template('home.html')

interga_dev/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR" dir="ltr" data-bs-theme="light">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Acesso Exclusivo Socinal SA">
  <meta name="author" content="Tecnologia Socinal">
  <meta name="robots" content="noindex, nofollow">
  <title>
    {% block title %}
    {% endblock %}
  </title>
  <!-- Links para Favicon -->
  <link rel="apple-touch-icon" href="{{ url_for('static', filename='img/favicon.png') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}">
  <!-- Links da Bibliotecas CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='libraries/bootstrap/css/bootstrap.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='libraries/bootstrap-icons/bootstrap-icons.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='libraries/fontawesome/css/all.min.css') }}">
  <!-- Links dos arquivos CSS Customizados -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/template.css') }}">
  {% block css %}
  {% endblock %}
</head>
<body>
  {% with messages = get_flashed_messages(with_categories=true)  %}
    {% if messages %}
      <div class="fixed-top mt-5">
        {% for category, message in messages %}
        <div class="row justify-content-center">
          <div class="col-auto">
            <div class="alert alert-{{ category }} alert-dismissible fade show p-2 mb-2 pointer autoCloseAlert" data-bs-dismiss="alert" role="alert">
              <i class="fa-solid fa-circle-info fa-1x"></i> <span class="me-3">{{ message }}</span>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
  <header>
    {% block header %}
    {% endblock %}
  </header>
  <main class="container-fluid">
    {% block main %}
    {% endblock %}
  </main>
  <footer>
    {% block footer %}
    {% endblock %}
  </footer>

  <!-- TOAST para Notificações -->
  <!-- <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header text-black" id="header_toast">
        <span id="ico_toast"></span>
        <strong class="ms-2 me-auto" id="titulo_toast"></strong>
        <small id="tempo_toast"></small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body" id="body_toast"></div>
    </div>
  </div> -->

  {% block modal %}
  {% endblock %}

  <!-- Adicione o link para o Bibliotecas JS -->
  <script src="{{ url_for('static', filename='libraries/jquery/jquery-3.7.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='libraries/bootstrap/js/bootstrap.bundle.js') }}"></script>
  <!-- Links dos arquivos JS Customizados -->
  <script src="{{ url_for('static', filename='js/template.js') }}"></script>
  {% block js %}
  {% endblock %}
</body>
</html>

interga_dev/templates/home.html
{% extends 'base.html' %}

{% block title %}
  Home - Socinal APIs Docs
{% endblock %}

{% block header %}
  {% include 'menu.html' %}
{% endblock %}

{% block main %}
  <div class="row">
    <div class="col-2">
      <div class="list-group border border-0" id="list-tab">
        <a class="list-group-item list-group-item-action active border border-0" id="list-home-list" data-bs-toggle="list" href="#list-home">Home</a>
        <a class="list-group-item list-group-item-action border border-0" id="list-profile-list" data-bs-toggle="list" href="#list-profile">Profile</a>
        <a class="list-group-item list-group-item-action border border-0" id="list-messages-list" data-bs-toggle="list" href="#list-messages">Messages</a>
        <a class="list-group-item list-group-item-action border border-0" id="list-settings-list" data-bs-toggle="list" href="#list-settings">Settings</a>
      </div>
    </div>
    <div class="col-10">
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="list-home">
          {{ lipsum(n=5, html=True, min=20, max=100) }}
        </div>
        <div class="tab-pane fade" id="list-profile">
          {{ lipsum(n=5, html=True, min=20, max=100) }}
        </div>
        <div class="tab-pane fade" id="list-messages">
          {{ lipsum(n=5, html=True, min=20, max=100) }}
        </div>
        <div class="tab-pane fade" id="list-settings">
          {{ lipsum(n=5, html=True, min=20, max=100) }}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

interga_dev/templates/login.html
{% extends 'base.html' %}

{% block title %}
  Login - Socinal APIs Docs
{% endblock %}

{% block header %}
  {% include 'usuarios/menu.html' %}
{% endblock %}

{% block main %}
<div class="container center">
  <div class="card w-18r bg-transparent-0">
    <div class="card-body bg-transparent-035">
      <p class="card-title text-center">
        <img class="mb-3" src="{{ url_for('static', filename='img/logo.png') }}" alt="Logo"><br>
        <span class="h4 ff-myriadpro-bold">Tarefas Alerta!</span>
      </p>
      <form action="{{ url_for('index') }}" method="POST" id="form_login">
        {{ login_form.hidden_tag() }}
        {{ login_form.next() }}
        <div class="row mb-3">
          <div class="col">
            {{ login_form.login.label(class='fw-bold') }}
            {% if login_form.login.errors %}
              {{ login_form.login(class='form-control is-invalid', placeholder="Informe seu login") }}
              <div class="invalid-feedback">
                {% for error in login_form.login.errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% else %}
              {{ login_form.login(class='form-control', placeholder="Informe seu login") }}
            {% endif %}
          </div>
        </div>
        <div class="row mb-2">
          <div class="col">
            {{ login_form.senha.label(class='fw-bold') }}
            {% if login_form.senha.errors %}
              {{ login_form.senha(class='form-control is-invalid', placeholder="Digite sua senha") }}
              <div class="invalid-feedback">
                {% for error in login_form.senha.errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% else %}
              {{ login_form.senha(class='form-control', placeholder="Digite sua senha") }}
            {% endif %}
          </div>
        </div>
        <div class="row mb-4">
          <div class="col text-center">
            {{ login_form.lembrar_dados(class='form-check-input') }}
            {{ login_form.lembrar_dados.label(class='form-check-label') }}
          </div>
        </div>
        <div class="row">
          <div class="col text-center">
          <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary" id="entrar">Entrar</button>
          </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

interga_dev/templates/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary shadow-sm mb-2">
  <div class="container-fluid">
    <a class="navbar-brand py-0" href="#">
      <img src="{{ url_for('static', filename='img/logo-h.png') }}" alt="Logo" height="30px">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menu_principal"
      aria-controls="menu_principal" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="menu_principal">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link <?php echo $active_home; ?>" href="{{ url_for('visitantes.home') }}"><i class="fa-solid fa-laptop-code"></i> Introdução</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php echo $active_tarefas; ?>" href=""><i class="fa-solid fa-fingerprint"></i> Autentição</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php echo $active_tarefas; ?>" href=""><i class="fa-solid fa-money-bill-transfer"></i> Operações</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php echo $active_tarefas; ?>" href=""><i class="fa-solid fa-file-invoice"></i> Cobrança</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php echo $active_tarefas; ?>" href=""><i class="fa-solid fa-magnifying-glass-dollar"></i> Consultas</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="menu_tema" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-brightness-high-fill"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="menu_tema">
            <li><a class="dropdown-item fw-bold pointer" id="modo_claro"><i class="bi bi-brightness-high-fill"></i> Modo Claro</a></li>
            <li><a class="dropdown-item pointer" id="modo_escuro"><i class="bi bi-moon-stars-fill"></i> Modo Escuro</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>